{% set name = "pykern" %}
{% set version = "20200824.233924" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: d0284fd4f9f457d585fd70874f45e2c5b134a37d65a67cdc92b339a2c5286ac1

build:
  noarch: python
  number: 0
  entry_points:
    - pykern = pykern.pykern_console:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - argh >=0.26
    - future >=0.14
    - github3.py >=1.1
    - jinja2 >=2.7
    - py-cpuinfo >=0.2
    - py >=1.4
    - pytest >=2.7,<=3.2.3
    - pytest-forked >=0.2
    - pytz >=2015.4
    - pyyaml >=3.0
    - requests >=2.18
    - setuptools >=20.3
    - six >=1.9
    - sphinx >=1.3.5
    - twine >=1.9
    - tox >=1.9
    - path.py >=7.7.1
    - python-dateutil >=2.4.2

test:
  imports:
    - pykern
    - pykern.pkcli
  commands:
    - pykern --help
  requires:
    - pytest

about:
  home: http://pykern.org
  license: Apache Software License
  license_family: APACHE
  license_file: LICENSE
  summary: Python application support
